name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_environment:
    name: Set up Python and R Environments
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("caret", "ggplot2", "forecast", "mlr3", "futile.logger"))'
          Rscript -e 'source("R/setup_dependencies.R")'

  run_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: setup_environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python tests
        run: |
          python -m unittest discover -s tests/

      - name: Run R tests
        run: |
          Rscript -e 'testthat::test_dir("tests/")'

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS
        run: |
          python deployment/scripts/deploy_aws.py

      - name: Deploy to GCP
        run: |
          python deployment/scripts/deploy_gcp.py